const Tikets = [
  {
    id: 1,
    date: "2021-12-01",
    from: "Milano",
    to: "Roma",
    vehicle: "Aereo",
    price: 20,
  },
  {
    id: 2,
    date: "2021-12-01",
    from: "Roma",
    to: "Milano",
    vehicle: "Aereo",
    price: 40,
  },
  {
    id: 3,
    date: "2021-11-30",
    from: "Milano",
    to: "Roma",
    vehicle: "Aereo",
    price: 55,
  },
  {
    id: 4,
    date: "2022-06-03",
    from: "Napoli",
    to: "Torino",
    vehicle: "Aereo",
    price: 60,
  },
  {
    id: 5,
    date: "2022-01-02",
    from: "Venezia",
    to: "Milano",
    veichle: "Aereo",
    price: 60,
  },
  {
    id: 6,
    date: "2021-09-13",
    from: "Napoli",
    to: "Torino",
    vehicle: "Aereo",
    price: 20,
  },
  {
    id: 7,
    date: "2021-12-01",
    from: "Roma",
    to: "Milano",
    vehicle: "Aereo",
    price: 100,
  },
  {
    id: 8,
    date: "2021-11-30",
    from: "Milano",
    to: "Roma",
    vehicle: "Aereo",
    price: 60,
  },
  {
    id: 9,
    date: "2021-09-22",
    from: "Torino",
    to: "Napoli",
    vehicle: "Aereo",
    price: 40,
  },
  {
    id: 10,
    date: "2021-12-02",
    from: "Milano",
    to: "Roma",
    veichle: "Aereo",
    price: 70,
  },
];

module.exports = Tikets

